version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "5100:5100"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis